# Generated by Django 6.0.6 on 2026-08-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_alter_task_phone_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='amount',
            field=models.IntegerField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
