# Generated by Django 6.0.6 on 2026-08-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0004_task_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='amount',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
