# Generated by Django 6.0.6 on 2026-08-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0005_alter_task_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='communication_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
